##
# ScandiPWA_CustomerDownloadableGraphQl
#
# @category    ScandiPWA
# @package     ScandiPWA_CustomerDownloadableGraphQl
# @copyright   Copyright © 2018 Scandiweb, Ltd (https://scandiweb.com)
# @copyright   Modifications © Selveq. All rights reserved.
# @license     OSL-3.0 (Open Software License ("OSL") v. 3.0)
# See LICENSE for license details.
##

type Query {
    customerDownloadableProducts: CustomerDownloadableProducts @resolver(class: "ScandiPWA\\CustomerDownloadableGraphQl\\Model\\Resolver\\CustomerDownloadableProducts") @doc(description: "The query returns the contents of a customer's downloadable products") @cache(cacheable: false)
}

type CustomerDownloadableProduct {
    title: String
    link_title: String
    order_id: Int
}
